name: Update Sitemap Dates
on:
  push:
    paths:
      - '**/schema.jsonld'
      - '**/*.yaml'
      
jobs:
  update-sitemap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Update Lastmod Dates
        run: |
          TODAY=$(date +%Y-%m-%d)
          sed -i "s|<lastmod>.*</lastmod>|<lastmod>$TODAY</lastmod>|g" sitemap.xml
          
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap lastmod dates" || echo "No changes to commit"
          git push